milky.vehicles.insertMany([
    { type: "Bicycle", station: "Library Lawns", available: true },
    { type: "Bicycle", station: "Library Lawns", available: false },
    { type: "Bicycle", station: "Library Lawns", available: true },
    { type: "Bicycle", station: "Bozolli", available: false },
    { type: "Bicycle", station: "Bozolli", available: true },
    { type: "Bicycle", station: "Bozolli", available: false },
    { type: "Bicycle", station: "Wits Science Stadium", available: true },
    { type: "Bicycle", station: "Wits Science Stadium", available: false },
    { type: "Bicycle", station: "Wits Science Stadium", available: true },
    { type: "Bicycle", station: "Hall 29", available: false },
    { type: "Bicycle", station: "Hall 29", available: true },
    { type: "Bicycle", station: "Hall 29", available: false },
    { type: "Skateboard", station: "Hall 29", available: true },
    { type: "Skateboard", station: "Library Lawns", available: false },
    { type: "Skateboard", station: "Wits Science Stadium", available: true },
    { type: "Skateboard", station: "Bozolli", available: false },
    { type: "Scooter", station: "Library Lawns", available: true },
    { type: "Scooter", station: "Library Lawns", available: false },
    { type: "Scooter", station: "Wits Science Stadium", available: true },
    { type: "Scooter", station: "Wits Science Stadium", available: false },
    { type: "Scooter", station: "Hall 29", available: true },
    { type: "Scooter", station: "Hall 29", available: false },
    { type: "Scooter", station: "Bozolli", available: true },
    { type: "Scooter", station: "Bozolli", available: false }
]);
